### ISSUE TITLE
why cannot compile Test.java ?

### ISSUE THREAD

**Issue by abiyogahendra** [ABusyProgrammer/PlagiarismDetector#9]
when i run "java Test.java" it has error => 

Test.java:73: error: cannot find symbol
                        double value = DriverProgram.driverProgram(origin, duplicate);
                                       ^
  symbol:   variable DriverProgram
  location: class Test
1 error

-

**Comment by ABusyProgrammer** [comment]
Hi @abiyogahendra, I am unable to replicate the error you are encountering. Could you provide the following details:
- Are you using your own text files, or are you using the ones that come with this project (in the Evaluation folder)?
- Some details on the environment in which you are running this program (Java version, OS, ...)?

**Comment by abiyogahendra** [comment]
im use windows 10 pro, 13.0.1 java versions,
.
im just following your step of installation on readme file and error in step 4

**Comment by ABusyProgrammer** [comment]
I am also using the same environment; however, I'm still not able to replicate this issue. The program works for me when I use Git Bash and Windows 10's command line.

I have updated the project to work in the command-line directly; please follow the instructions again, and re-clone the updated project. Let me know if you run into the same problem.

**Comment by ABusyProgrammer** [comment]
There is a lack of activity on this issue; it will be closed for now.
